name: one-tagumvision
region: sgp

databases:
- name: gistagum-db
  engine: PG
  production: false
  version: "15"
  plan: db-s-dev-database

services:
- name: gisonetagumvision
  github:
    repo: kennethkeeen/GISONETAGUMVISION
    branch: main
    deploy_on_push: true
  dockerfile_path: Dockerfile
  source_dir: /
  http_port: 8000
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb
  envs:
  - key: DJANGO_SETTINGS_MODULE
    scope: RUN_AND_BUILD_TIME
    value: gistagum.settings
  - key: DJANGO_SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: DEBUG
    scope: RUN_AND_BUILD_TIME
    value: "false"
  - key: ALLOWED_HOSTS
    scope: RUN_AND_BUILD_TIME
    value: '*.ondigitalocean.app'
  - key: CSRF_TRUSTED_ORIGINS
    scope: RUN_AND_BUILD_TIME
    value: https://*.ondigitalocean.app
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    value: ${gistagum-db.DATABASE_URL}
    type: SECRET
  health_check:
    http_path: /health/
    initial_delay_seconds: 90
  routes:
  - path: /
