name: one-tagumvision
region: sgp

databases:
- name: gistagum-db
  engine: PG
  production: false
  version: "15"
  plan: db-s-dev-database

services:
- name: gisonetagumvision
  github:
    repo: kennethkeeen/GISONETAGUMVISION
    branch: main
    deploy_on_push: true
  dockerfile_path: Dockerfile
  source_dir: /
  http_port: 8000
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb
  # Auto-scaling configuration (optional - uncomment to enable)
  # autoscaling:
  #   min_instances: 1
  #   max_instances: 3
  #   metrics:
  #     cpu_percent:
  #       target: 70
  # Performance optimizations
  # Use the container CMD (start.sh) so migrations + collectstatic run on deploy.
  run_command: /app/start.sh
  envs:
  - key: DJANGO_SETTINGS_MODULE
    scope: RUN_AND_BUILD_TIME
    value: gistagum.settings
  - key: DJANGO_SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: DEBUG
    scope: RUN_AND_BUILD_TIME
    value: "false"
  - key: ALLOWED_HOSTS
    scope: RUN_AND_BUILD_TIME
    value: '*.ondigitalocean.app'
  - key: CSRF_TRUSTED_ORIGINS
    scope: RUN_AND_BUILD_TIME
    value: https://*.ondigitalocean.app
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    value: ${gistagum-db.DATABASE_URL}
    type: SECRET
  - key: REDIS_URL
    scope: RUN_AND_BUILD_TIME
    value: redis://default:YOUR_PASSWORD@YOUR_HOST:YOUR_PORT
    type: SECRET
  health_check:
    http_path: /health/
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  routes:
  - path: /
  volumes:
  - mount_path: /app/media
    name: media-storage
    size_gigabytes: 2

# Worker component for background tasks (Celery)
- name: gisonetagumvision-worker
  github:
    repo: kennethkeeen/GISONETAGUMVISION
    branch: main
    deploy_on_push: true
  dockerfile_path: Dockerfile
  source_dir: /
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb
  run_command: celery -A gistagum worker --loglevel=info --concurrency=2 --uid=nobody --gid=nogroup
  envs:
  - key: DJANGO_SETTINGS_MODULE
    scope: RUN_AND_BUILD_TIME
    value: gistagum.settings
  - key: DJANGO_SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: DEBUG
    scope: RUN_AND_BUILD_TIME
    value: "false"
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    value: ${gistagum-db.DATABASE_URL}
    type: SECRET
  - key: REDIS_URL
    scope: RUN_AND_BUILD_TIME
    value: redis://default:YOUR_PASSWORD@YOUR_HOST:YOUR_PORT
    type: SECRET
  - key: CELERY_WORKER
    scope: RUN_AND_BUILD_TIME
    value: "true"
