# Generated by Django 5.2.1 on 2025-05-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeng', '0008_projectdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Project progress in percentage (0-100)', null=True),
        ),
    ]
