# Generated by Django 5.2.1 on 2025-11-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeng', '0012_add_database_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangayMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('land_area', models.DecimalField(blank=True, decimal_places=2, help_text='Land area in km²', max_digits=10, null=True)),
                ('density', models.DecimalField(blank=True, decimal_places=2, help_text='Population density in people/km²', max_digits=10, null=True)),
                ('growth_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Population growth rate in %', max_digits=5, null=True)),
                ('barangay_class', models.CharField(blank=True, choices=[('urban', 'Urban'), ('rural', 'Rural')], help_text='Urban or Rural classification', max_length=10, null=True)),
                ('economic_class', models.CharField(blank=True, choices=[('growth_center', 'Growth Center'), ('emerging', 'Emerging'), ('satellite', 'Satellite')], help_text='Economic development classification', max_length=20, null=True)),
                ('elevation_type', models.CharField(blank=True, choices=[('highland', 'Highland/Rolling'), ('plains', 'Plains/Lowland'), ('coastal', 'Coastal')], help_text='Geographic elevation classification', max_length=20, null=True)),
                ('industrial_zones', models.JSONField(default=list, help_text='List of industrial zone types (can be multiple)')),
                ('primary_industries', models.JSONField(default=list, help_text='List of primary industries (agriculture, tourism, etc.)')),
                ('special_features', models.JSONField(default=list, help_text='Special facilities (hospitals, markets, ports, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.CharField(default='PSA-2020 CPH', help_text='Source of demographic data', max_length=255)),
                ('data_year', models.IntegerField(default=2020, help_text='Year of data collection')),
            ],
            options={
                'verbose_name_plural': 'Barangay Metadata',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='projeng_notif_recip_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='projeng_notif_recip_read_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='projeng_pro_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='projeng_pro_barangay_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='projeng_pro_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='projeng_pro_updated_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='projeng_pro_dates_idx',
        ),
        migrations.RemoveIndex(
            model_name='projectcost',
            name='projeng_proj_proj_cost_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='projectprogress',
            name='projeng_proj_proj_date_idx',
        ),
    ]
