# Generated by Django 5.2.1 on 2025-11-14 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeng', '0016_suitabilitycriteria_landsuitabilityanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(choices=[('single_family_house', 'Single Family House'), ('multi_family_house', 'Multi-Family House'), ('apartment_building', 'Apartment Building (3-5 stories)'), ('high_rise_residential', 'High-Rise Residential (6+ stories)'), ('socialized_housing', 'Socialized Housing'), ('retail_store', 'Retail Store'), ('shopping_mall', 'Shopping Mall'), ('office_building', 'Office Building'), ('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('light_industrial', 'Light Industrial Facility'), ('heavy_industrial', 'Heavy Industrial Facility'), ('warehouse', 'Warehouse'), ('factory', 'Factory'), ('road', 'Road/Highway'), ('bridge', 'Bridge'), ('water_system', 'Water System'), ('sewer_system', 'Sewer System'), ('school', 'School'), ('hospital', 'Hospital'), ('government_building', 'Government Building'), ('church', 'Church/Religious Building'), ('park', 'Park/Recreation'), ('cemetery', 'Cemetery')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('density_level', models.CharField(choices=[('low', 'Low Density'), ('medium', 'Medium Density'), ('high', 'High Density')], help_text='Density level of this project type', max_length=20)),
                ('height_category', models.CharField(blank=True, choices=[('low', 'Low (1-2 stories)'), ('medium', 'Medium (3-5 stories)'), ('high', 'High (6+ stories)')], max_length=20, null=True)),
                ('requires_industrial', models.BooleanField(default=False, help_text='Requires industrial zone')),
                ('requires_commercial', models.BooleanField(default=False, help_text='Requires commercial zone')),
                ('requires_residential', models.BooleanField(default=False, help_text='Requires residential zone')),
            ],
            options={
                'verbose_name': 'Project Type',
                'verbose_name_plural': 'Project Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ZoneAllowedUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_type', models.CharField(choices=[('R1', 'Low Density Residential'), ('R2', 'Medium Density Residential'), ('R3', 'High Density Residential'), ('SHZ', 'Socialized Housing Zone'), ('C1', 'Major Commercial Zone'), ('C2', 'Minor Commercial Zone'), ('I1', 'Heavy Industrial Zone'), ('I2', 'Light and Medium Industrial Zone'), ('Al', 'Agro-Industrial'), ('In', 'Institutional'), ('Ag', 'Agricultural'), ('Cu', 'Cultural')], db_index=True, max_length=10)),
                ('is_primary_use', models.BooleanField(default=True, help_text='Primary allowed use (vs conditional use)')),
                ('is_conditional', models.BooleanField(default=False, help_text='Requires special permit/approval')),
                ('conditions', models.TextField(blank=True, help_text='Conditions or restrictions for this use')),
                ('max_density', models.CharField(blank=True, help_text="Maximum density allowed (e.g., '50 units/hectare')", max_length=50)),
                ('max_height', models.CharField(blank=True, help_text="Maximum height allowed (e.g., '5 stories')", max_length=50)),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_zones', to='projeng.projecttype')),
            ],
            options={
                'verbose_name': 'Zone Allowed Use',
                'verbose_name_plural': 'Zone Allowed Uses',
                'indexes': [models.Index(fields=['zone_type'], name='projeng_zon_zone_ty_309e35_idx')],
                'unique_together': {('zone_type', 'project_type')},
            },
        ),
        migrations.CreateModel(
            name='ZoneRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_zone', models.CharField(help_text='Recommended zone type', max_length=10)),
                ('overall_score', models.FloatField(help_text='Overall MCDA score (0-100)')),
                ('zoning_compliance_score', models.FloatField(default=0)),
                ('land_availability_score', models.FloatField(default=0)),
                ('accessibility_score', models.FloatField(default=0)),
                ('community_impact_score', models.FloatField(default=0)),
                ('infrastructure_score', models.FloatField(default=0)),
                ('rank', models.IntegerField(help_text='Rank among all recommendations (1 = best)')),
                ('reasoning', models.TextField(help_text='Why this zone is recommended')),
                ('advantages', models.JSONField(default=list, help_text='List of advantages for this zone')),
                ('constraints', models.JSONField(default=list, help_text='List of constraints or limitations')),
                ('is_selected', models.BooleanField(default=False, help_text='Whether this recommendation was selected')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_recommendations', to='projeng.project')),
            ],
            options={
                'verbose_name': 'Zone Recommendation',
                'verbose_name_plural': 'Zone Recommendations',
                'ordering': ['project', 'rank'],
                'unique_together': {('project', 'recommended_zone')},
            },
        ),
    ]
