# Generated by Django 5.2.1 on 2026-01-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeng', '0023_budgetrequest_budgetrequestattachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceOfFunds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Sources of Funds',
                'ordering': ['name'],
            },
        ),
    ]
