# Generated by Django 5.2.1 on 2026-01-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeng', '0024_sourceoffunds'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='purok',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
