# Generated by Django 5.2.1 on 2026-01-24 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeng', '0025_project_purok'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprogress',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectprogress',
            name='last_edit_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projectprogress',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_updates_edited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProjectProgressEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('from_percentage', models.IntegerField()),
                ('to_percentage', models.IntegerField()),
                ('from_description', models.TextField(blank=True, null=True)),
                ('to_description', models.TextField(blank=True, null=True)),
                ('from_justification', models.TextField(blank=True, null=True)),
                ('to_justification', models.TextField(blank=True, null=True)),
                ('edit_reason', models.TextField(help_text='Reason for editing this progress update')),
                ('added_photos_count', models.IntegerField(default=0)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('progress_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='projeng.projectprogress')),
            ],
            options={
                'ordering': ['-edited_at'],
            },
        ),
    ]
