# Generated by Django 5.2.1 on 2026-01-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeng', '0026_projectprogress_is_edited_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='purok',
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='code',
            field=models.CharField(choices=[('single_family_house', 'Single Family House'), ('multi_family_house', 'Multi-Family House'), ('apartment_building', 'Apartment Building (3-5 stories)'), ('high_rise_residential', 'High-Rise Residential (6+ stories)'), ('socialized_housing', 'Socialized Housing'), ('retail_store', 'Retail Store'), ('shopping_mall', 'Shopping Mall'), ('office_building', 'Office Building'), ('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('light_industrial', 'Light Industrial Facility'), ('heavy_industrial', 'Heavy Industrial Facility'), ('warehouse', 'Warehouse'), ('factory', 'Factory'), ('road', 'Road/Highway'), ('bridge', 'Bridge'), ('water_system', 'Water System'), ('sewer_system', 'Sewer System'), ('school', 'School'), ('hospital', 'Hospital'), ('government_building', 'Government Building'), ('church', 'Church/Religious Building'), ('park', 'Park/Recreation'), ('cemetery', 'Cemetery'), ('gad', 'GAD (Gender and Development)')], max_length=50, unique=True),
        ),
    ]
