# Generated by Django 5.2.1 on 2026-02-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeng', '0028_alter_projecttype_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='prn',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
