# Generated by Django 5.2.1 on 2026-03-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeng', '0032_projectconfiguredprogress_projectextensionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcost',
            name='cost_type',
            field=models.CharField(
                choices=[
                    ('material', 'Material'),
                    ('labor', 'Labor'),
                    ('equipment', 'Equipment'),
                    ('ocm', 'OCM'),
                    ('contingency', 'Contingency'),
                    ('supply and install', 'Supply and Install'),
                    ('permit&licenses', 'Permit&Licenses'),
                    ('other', 'Other'),
                ],
                max_length=20,
            ),
        ),
    ]
