# Generated by Django 5.2.1 on 2026-03-03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projeng", "0033_alter_projectcost_cost_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCostAllocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("material", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("labor", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("equipment", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("supply_and_install", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("ocm", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("permit_and_licenses", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("contingency", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("project", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="cost_allocation", to="projeng.project")),
                ("set_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="project_cost_allocations_set", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
