# Generated by Django 5.2.1 on 2026-03-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeng", "0034_projectcostallocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="day_count_type",
            field=models.CharField(
                choices=[("working_days", "Working days"), ("calendar_days", "Calendar days")],
                default="working_days",
                max_length=20,
            ),
        ),
    ]
