# Generated by Django 5.2.1 on 2026-03-05 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeng', '0035_project_day_count_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='receipts/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_receipts', to='projeng.projectcost')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
