# Generated by Django 5.2.1 on 2026-02-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_alter_project_options_project_assigned_engineers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='prn',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
